events {}

http {

    # FRONTEND
    server {
        listen 80;
        server_name trading.digitalwaveitsolution.online;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
        }
    }

    # BACKEND API
    server {
        listen 80;
        server_name trading-api.digitalwaveitsolution.online;

        location / {
            proxy_pass http://backend:5000;
            proxy_set_header Host $host;
        }
    }
}
