events {}

http {
    server {
        listen 80;

        # ✅ API (NO REWRITE)
        location /api/ {
            proxy_pass http://indian-market-ai-backend:5000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ✅ FRONTEND
        location / {
            proxy_pass http://indian-market-ai-frontend:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
    }
}
