const ORDER_STATES = Object.freeze({
  INTENT_CREATED: 'INTENT_CREATED',
  RISK_APPROVED: 'RISK_APPROVED',
  SUBMITTING: 'SUBMITTING',
  SUBMITTED: 'SUBMITTED',
  ACKED: 'ACKED',
  PARTIAL_FILLED: 'PARTIAL_FILLED',
  FILLED: 'FILLED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED'
});

const TERMINAL_STATES = new Set([
  ORDER_STATES.FILLED,
  ORDER_STATES.CANCELLED,
  ORDER_STATES.REJECTED,
  ORDER_STATES.FAILED
]);

const ALLOWED_TRANSITIONS = Object.freeze({
  [ORDER_STATES.INTENT_CREATED]: [ORDER_STATES.RISK_APPROVED, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.RISK_APPROVED]: [ORDER_STATES.SUBMITTING, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.SUBMITTING]: [ORDER_STATES.SUBMITTED, ORDER_STATES.ACKED, ORDER_STATES.FAILED],
  [ORDER_STATES.SUBMITTED]: [ORDER_STATES.ACKED, ORDER_STATES.PARTIAL_FILLED, ORDER_STATES.FILLED, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.ACKED]: [ORDER_STATES.PARTIAL_FILLED, ORDER_STATES.FILLED, ORDER_STATES.CANCEL_REQUESTED, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.PARTIAL_FILLED]: [ORDER_STATES.FILLED, ORDER_STATES.CANCEL_REQUESTED, ORDER_STATES.CANCELLED, ORDER_STATES.FAILED],
  [ORDER_STATES.CANCEL_REQUESTED]: [ORDER_STATES.CANCELLED, ORDER_STATES.FILLED, ORDER_STATES.FAILED],
  [ORDER_STATES.FILLED]: [],
  [ORDER_STATES.CANCELLED]: [],
  [ORDER_STATES.REJECTED]: [],
  [ORDER_STATES.FAILED]: []
});

function canTransition(from, to) {
  return ALLOWED_TRANSITIONS[from]?.includes(to) || false;
}

function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid order state transition: ${from} -> ${to}`);
  }
  return true;
}

module.exports = {
  ORDER_STATES,
  TERMINAL_STATES,
  canTransition,
  assertTransition
};
