const ORDER_STATES = Object.freeze({
  INTENT_CREATED: 'INTENT_CREATED',
  RISK_CHECK_PASSED: 'RISK_CHECK_PASSED',
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVED: 'APPROVED',
  SENT_TO_BROKER: 'SENT_TO_BROKER',
  OPEN: 'OPEN',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  FILLED: 'FILLED',
  CANCELLED: 'CANCELLED',
  EXIT_PENDING: 'EXIT_PENDING',
  EXITED: 'EXITED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED',

  // Backward-compatible aliases for older services/tests during migration.
  RISK_APPROVED: 'RISK_CHECK_PASSED',
  SUBMITTING: 'APPROVED',
  SUBMITTED: 'SENT_TO_BROKER',
  ACKED: 'OPEN',
  PARTIAL_FILLED: 'PARTIALLY_FILLED',
  CANCEL_REQUESTED: 'EXIT_PENDING'
});

const TERMINAL_STATES = new Set([
  ORDER_STATES.FILLED,
  ORDER_STATES.CANCELLED,
  ORDER_STATES.EXITED,
  ORDER_STATES.REJECTED,
  ORDER_STATES.FAILED
]);

const ALLOWED_TRANSITIONS = Object.freeze({
  [ORDER_STATES.INTENT_CREATED]: [ORDER_STATES.RISK_CHECK_PASSED, ORDER_STATES.APPROVAL_PENDING, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.RISK_CHECK_PASSED]: [ORDER_STATES.APPROVAL_PENDING, ORDER_STATES.APPROVED, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.APPROVAL_PENDING]: [ORDER_STATES.APPROVED, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.APPROVED]: [ORDER_STATES.SENT_TO_BROKER, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.SENT_TO_BROKER]: [ORDER_STATES.OPEN, ORDER_STATES.PARTIALLY_FILLED, ORDER_STATES.FILLED, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.OPEN]: [ORDER_STATES.PARTIALLY_FILLED, ORDER_STATES.FILLED, ORDER_STATES.EXIT_PENDING, ORDER_STATES.REJECTED, ORDER_STATES.FAILED],
  [ORDER_STATES.PARTIALLY_FILLED]: [ORDER_STATES.FILLED, ORDER_STATES.EXIT_PENDING, ORDER_STATES.CANCELLED, ORDER_STATES.FAILED],
  [ORDER_STATES.EXIT_PENDING]: [ORDER_STATES.EXITED, ORDER_STATES.CANCELLED, ORDER_STATES.FILLED, ORDER_STATES.FAILED],
  [ORDER_STATES.FILLED]: [],
  [ORDER_STATES.CANCELLED]: [],
  [ORDER_STATES.EXITED]: [],
  [ORDER_STATES.REJECTED]: [],
  [ORDER_STATES.FAILED]: []
});

function canTransition(from, to) {
  return ALLOWED_TRANSITIONS[from]?.includes(to) || false;
}

function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid order state transition: ${from} -> ${to}`);
  }
  return true;
}

module.exports = {
  ORDER_STATES,
  TERMINAL_STATES,
  canTransition,
  assertTransition
};
